dist: bionic
language: python

install:
  - pip3 install --upgrade pip wheel pytest tox virtualenv
  # Install dependencies (uses $TOXENV)
  - tox --notest

# Default script if not overridden
script:
  - ulimit -n 4096
  # Test (uses $TOXENV, uses environment from previous step)
  - tox

jobs:
  include:
    - name: Windows
      os: windows
      language: sh
      before_install:
        - choco install python3 --version 3.7.3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
      env: TOXENV=py37
      install:
        - python -m pip install --upgrade pip wheel pytest tox
        - tox --notest
      script:
        - tox
    - name: OS X
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      env: TOXENV=py37
    - name: Python37
      python: "3.7"
      env: TOXENV=py37
    - name: Python36
      python: "3.6"
      env: TOXENV=py36
    - name: Python38
      python: "3.8"
      env: TOXENV=py38

    - stage: deploy
      python: "3.6"
      if: tag IS present
      install: skip
      script: skip
      skip_cleanup: true
      deploy:
        provider: pypi
        user: $PYPI_USER
        password: $PYPI_PASSWORD
        distributions: sdist bdist_wheel
        on:
          tags: true

cache:
  directories:
  - $HOME/.cache/pip
