---
language: generic

services:
  - docker

matrix:
  include:
    - os: linux
      env:
        - PLATFORM=docker
    - os: linux
      env:
        - PACKAGE_NAME=omero-py
        - PLATFORM=miniconda
        - REQUIREMENTS_CHANNEL=manics

install:
  - ./ci/travis-install.sh

script:
  - ./ci/travis-script.sh

deploy:
  - provider: pypi
    user: $PYPI_USER
    password: $PYPI_PASSWORD
    env:
      - PLATFORM=docker
    on:
      tags: true

  # Anaconda builds include a label $TRAVIS_BRANCH and can be overwritten
  - provider: script
    skip_cleanup: true
    script: ./ci/travis-deploy.sh --force -l "${TRAVIS_BRANCH}"
    env:
      - PLATFORM=miniconda
    on:
      all_branches: true

  # Anaconda release
  - provider: script
    skip_cleanup: true
    script: ./ci/travis-deploy.sh
    env:
      - PLATFORM=miniconda
    on:
      tags: true
